### ISSUE TITLE
What is preventing Event Hub from working in Node?

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#90] opened 2023-03-22 10:21 UTC
Currently, according to the documentation, event hub doesn't work with Node.

From http://ftrack-javascript-api.rtd.ftrack.com/en/stable/handling_events.html:
> The event hub in the JavaScript API has some minor differences and lacks some of the features available in the [python counterpart](http://ftrack-python-api.rtd.ftrack.com/en/stable/handling_events.html#handling-events).

However, from my point of view, it looks like the `socket.io` client should work in Node out of the box: https://stackoverflow.com/questions/10703513/node-js-client-for-a-socket-io-server

Can you elaborate on what exactly isn't working for Node?

Because in that case, we could be interested in fixing it and contributing a pull request.

**Comment by gismya** [comment] 2023-03-22 10:45
Since updating versions of `socket.io` would incur breaking changes to our API, affecting customers' API clients, we are still on a version of `socket.io` that to my knowledge does not have a Node-compatible implementation.

**Comment by ffMathy** [comment] 2023-03-22 10:46
Aha. Interesting. Could this be part of the 2.0 milestone as well then?

**Comment by gismya** [comment] 2023-03-22 10:53
The main issue isn't with the client but with the server portion of the code. I know there have been discussions on updating that, but it's to my knowledge not on any current roadmap. I'll forward the request to the relevant team, always useful to have specific needs to fulfill when prioritizing.

**Comment by gismya** [comment] 2023-03-22 11:05
That is exactly what I mean, the issue is that the socket.io implementation in the backend ftrack code is for an older version of `socket.io`.

**Comment by ffMathy** [comment] 2023-03-22 11:09
Aha. I see. Which version of `socket.io` is the server using? Do we know? Maybe I can try to figure out if it would be breaking or not, or research in what it would take to add support to the existing one.

**Comment by ffMathy** [comment] 2023-04-04 07:01
I have confirmed that there is no mention of Node support in 0.9.17:
https://github.com/socketio/socket.io-client/tree/81089a2723770d5b32753485d1e5a160a72abab6

And that there is an explicit mention in 1.0.0:
https://github.com/socketio/socket.io-client/tree/367a9cb5a51d146e7e4bb1dd0d340eaf80de29ce

I will try running some experiments, and then I'll make a PR.

**Comment by ffMathy** [comment] 2023-04-04 08:50
I created a pull request now over at #96. It's a draft. It doesn't seem to work yet, but I am unsure if it is just because of some corporate VPN we have at work or something.

But perhaps it could be a starting point for you to go further, since I think I am a bit stuck? Right now, I am experiencing a timeout error. But the code compiles and runs.

Here is the code I used to experiment:

```typescript
import {Session} from '@ftrack/api';

const client = new Session(
    process.env.FTRACK_SERVER as any,
    process.env.FTRACK_API_USER as any,
    process.env.FTRACK_API_KEY as any
);

//this works.
client.query("select id from Project").then(console.log);

//this gets connection timeout.
client.eventHub.connect();

client.eventHub.subscribe('topic=*', (x: any) => {
    //this is never called due to the above timeout.
    console.log(x);
})
```

If you want a better repro example, I can also create that.

**Comment by ffMathy** [comment] 2023-04-07 10:03
If this could be fixed, we would be forever grateful. I suspect my branch might be connecting forever because of VPN or company firewall. Would be awesome if someone could try my branch on their machine, or perhaps solve the problem.

**Comment by ffMathy** [comment] 2023-04-11 09:31
Oh, not at all! And I'm super happy you're looking into this.

Right now, we have a server which forwards all of our events to an AWS SNS topic. 

Our plan is to then have AWS Lambdas (serverless functions) that respond to these. But for them to be able to "reply" to events like `action.discover` and `action.launch`, they need to be able to use the event hub.

And we do not have a lot of Python competencies in house, and Denmark is not very good for finding Python competencies in general, compared to other languages.

So until this somehow works, we're kind of stuck.

**Comment by ffMathy** [comment] 2023-04-13 20:15
I decided to go pick up my work computer and made another "interesting" experiment PR here:
https://github.com/ftrackhq/ftrack-javascript/pull/98

In this one, I tried "sacrificing" web compatibility temporarily, just to see if I can hack the existing socket.io-client code directly to work in Node.

I switched from using XMLHttpRequest to using https://www.npmjs.com/package/xmlhttprequest which also seems to be used by version 1.0.0.

Now, the "connect()" call is no longer freezing forever, so that's very interesting actually. Unfortunately it's timing out after a while.

I feel like we're getting closer though! I am inserting `debugger;` statements everywhere and attaching a debugger in Node to see if I can find the root cause.

Wireshark etc doesn't seem to be installable on my work machine (some policy thing I think).

**Comment by ffMathy** [comment] 2023-04-13 20:20
@gismya can you tell me more about the Event Hub API on the server-side? Is it just 100% websocket based? I don't know much about websockets. Can they be simulated by regular HTTP calls, or do they use TCP?

**Comment by gismya** [comment] 2023-04-14 06:43
> I now actually have time for this, but outside of working hours. And then I am not able to access my work computer, which has the company VPN, which can reach the Ftrack instance.
> 
> That's problematic. It would be super awesome if Ftrack offered some dummy cluster that everyone could use when contributing, or perhaps request access to.

We have free trial servers you can create here: https://www.ftrack.com/en/create-workspace. If that's not enough I can arrange something different :)

**Comment by gismya** [comment] 2023-04-14 06:48
> @gismya can you tell me more about the Event Hub API on the server-side? Is it just 100% websocket based? I don't know much about websockets. Can they be simulated by regular HTTP calls, or do they use TCP?

I don't know much more - the event hub predates my employment by about 10 years :)

Let me try to summon someone who might have more details: @lucaas

**Comment by ffMathy** [comment] 2023-04-14 11:17
> > @gismya can you tell me more about the Event Hub API on the server-side? Is it just 100% websocket based? I don't know much about websockets. Can they be simulated by regular HTTP calls, or do they use TCP?
> 
> I don't know much more - the event hub predates my employment by about 10 years :)
> 
> Let me try to summon someone who might have more details: @lucaas

Only 10 years? I thought it somehow predated the existence of JavaScript itself. An ancient relic whos origins are unknown.

**Comment by gismya** [comment] 2023-04-14 11:35
I've gathered more information about this internally. I'll try to summarise this during the weekend, and hopefully have time to write a minimal node implementation - mostly writing this so you'll remind me if I forget and haven't updated anything by next week :)

**Comment by ffMathy** [comment] 2023-04-14 14:16
Sounds awesome! 😍

**Comment by gismya** [comment] 2023-04-18 12:55
The bad news is that it looks like unless we launch a rewrite of the backend code, a full rewrite of the WebSocket client would probably be needed.

The good news is that the problem looked interesting, so I accidentally spent a few hours on a [re-implementation of socket.io](https://github.com/ftrackhq/ftrack-javascript/tree/rewrite-socketio-client). It's minimal but seems to cover most if not all use cases that the API has. Do some testing and see if it seems to work in Node as well — I only tested it in the browser so far.

![Nerd sniping](https://imgs.xkcd.com/comics/nerd_sniping.png)

**Comment by ffMathy** [comment] 2023-04-18 13:06
Hahahaha I love the XKCD!

If I find that socket.io to be working in Node, is there any chance it can be merged in and used instead, or as a fall-back in Node scenarios?

Because if so, I'd gladly test it!

Sounds like an awesome task! Damn, I am impressed!

**Comment by gismya** [comment] 2023-04-18 13:42
There is more than a chance, but I'll have to check with the rest of the development team if we can take the resources needed to merge this. Since it concerns parts of the application and integrations I've never touched it might need a thorough QA process, hence I can't give any promises.

Worst case, if it's enough for your use case you can always run a forked version :)

**Comment by ffMathy** [comment] 2023-04-19 06:00
That sounds great! I'll see if I can test this soon then.

I'd really like to avoid running a fork. But perhaps it might be necessary.

**Comment by ffMathy** [comment] 2023-04-19 06:35
I like what I am seeing, but it is not working in Node. But for reasons that should be fixable.

I get the following error:

```
/ftrack-javascript/source/simple_socketio.ts:191
    return this.ws?.readyState === WebSocket.OPEN;
                                             ^
TypeError: Cannot read properties of undefined (reading 'OPEN')
```

In addition, I noticed a few things.

1. When I run `npm run build`, I get compile errors. I worked around this by installing `@types/ws`.
2. After fixing the above error (by just providing a value of `1` instead of `WebSocket.OPEN`, I am instead getting an error that `WebSocket$1` is not a constructor.

Can you try to repro on Node? Not sure what to do about this unfortunately.

**Comment by gismya** [comment] 2023-04-19 07:49
Apparently it wasn't enough just installing `isomorphic-ws` and calling it a day. I'll see why that throws an error, feels like it shouldn't.

**Comment by gismya** [comment] 2023-04-19 09:18
Needed to explicitly tell `Vite` it was an external dependency. Now it's running and I can see it's connecting.

**Comment by ffMathy** [comment] 2023-04-24 17:24
Awesome stuff! Sorry for getting back to this so late. Lots of stuff popped up.

I got a chance to test it now.

This was my test code:

```typescript

import { Session } from '@ftrack/api';

const client = new Session(
    process.env.EVENT_PROXY_FTRACK_SERVER as any,
    process.env.EVENT_PROXY_FTRACK_API_USER as any,
    process.env.EVENT_PROXY_FTRACK_API_KEY as any
);

//this gets connection timeout.
client.eventHub.connect();

setTimeout(() => {
    console.log("connected?", client.eventHub.isConnected());
    client.eventHub.subscribe('topic=*', (x: any) => {
        console.log(x);
    })
}, 5000);
```

`isConnected` now returns `true`, but I am not receiving an event when I go in to Ftrack and change an entity. Any ideas why?

**Comment by gismya** [comment] 2023-04-25 05:30
Try subscribing to specifically the update topic instead of `*`. If it's not working I'll get to the Node parts once I'm done writing tests and verifying capabilities in the browser version.

**Comment by ffMathy** [comment] 2023-04-25 06:00
Is this a bug, or is the plan to not have support for wildcard topics?

Because that is unfortunately a relatively big limitation for us 🙂

**Comment by gismya** [comment] 2023-04-25 06:12
I see that wildcard topics are part of the Python API documentation, but not mentioned in the Javascript API documentation. 
We have started working on getting the Javascript API closer to feature parity with the Python API.

So if it was working before in the Javascript API, but undocumented (This has to be investigated), it should work after the current PR. If it's a new feature, then we can add a new issue about it and we'll make that a separate pull request.

**Comment by ffMathy** [comment] 2023-04-25 09:16
Using `ftrack.update` it actually seems to work!

Wildcard would be such an awesome feature to have though.

**Comment by gismya** [comment] 2023-04-25 09:56
Great to hear that it seems to be working in Node.

Please add an issue for that so that it's easy to pick up. I'll make some comparisons with the Python API to see how we should communicate wildcard topics with the server.

**Comment by ffMathy** [comment] 2023-04-25 10:28
See #101!

**Comment by gismya** [comment] 2023-05-23 13:11
After reviewing we realized that it wouldn't need to go into a major release. The beta release of 1.5 is out now, including both this and #101

**Comment by ffMathy** [comment] 2023-05-23 13:18
Mad skills. That's all I have to say! 😍

**Comment by ffMathy** [comment] 2023-07-19 08:28
@gismya can we re-open this since it is not resolved yet? Any updates on how it's going? We're still stuck on some beta version, which now has issues that have since been fixed by later releases.

**Comment by gismya** [comment] 2023-07-19 08:59
I agree, and I'm opening the issue again.  I've also made a new pre-release using the changes since the 1.5 beta was made and released as `v1.8.0-alpha1`. 
We had unexpected issues with the beta regarding how browser CORS is working with `fetch` vs `xhr` that are still in the new alpha, but everything should work fine for Node. Please report any issues you might find.

**Comment by ffMathy** [comment] 2023-07-19 09:58
Sure!

We've been using it for about 5 weeks now I think without any issues and active and regular development.

**Comment by ffMathy** [comment] 2023-07-19 13:04
It seems to be happening when I also (after listening) publish my own event:

```javascript
ftrackSession.eventHub.publish(new Event("my-namespace.started", {}, {}))
```

**Comment by ffMathy** [comment] 2023-07-19 15:20
I see that the events come from one of our quite heavily used ftrack instances, and that the source of the event is the Javascript client.

So perhaps the events are real. But I still feel like the python client has less of these.

By setting a subscriber ID filter for my custom event, I solved the issue.

**Comment by ffMathy** [comment] 2023-08-29 09:29
What is the ETA on getting the alpha out at the moment? Is everyone back from vacation? I'm asking because we're going live soon, and I'd love to know if it's safe to still use the alpha.

**Comment by gismya** [comment] 2023-08-29 11:51
It's completely safe to use. As long as other updates are being released (One is soon coming with the features merged today) the node-compatible build will continue to be updated alongside the main build until a solution with a fully node-compatible version of the event hub is the standard release. The only changes that might come before that are things not affecting the public-facing functions.

**Comment by ffMathy** [comment] 2023-09-11 06:50
Thanks for that update.

So far, we've primarily tested our actions flow through our end-to-end tests. But these just simulate events entirely on the hub.

Today we tried invoking an action via the Ftrack UI. And even though a discover event is being replied to, the action we provide is not visible. It just says it keeps looking.

Can you help us maybe do a sample action run in the alpha version of the package and see if it works for you?

**Comment by ffMathy** [comment] 2023-09-11 10:29
Here's a repro that's not working for us:

```typescript
import { Session } from '@ftrack/api';

const session = new Session(
    url,
    email,
    key
  );

session.eventHub.connect();

session.eventHub.subscribe(
    'topic=ftrack.action.discover',
    (event) => {
      console.log("Discover event received");
      const action = { items: [{ label: 'test', actionIdentifier: 'com.ftrack.brickissue' }] };
    //   session.eventHub.publishReply(event, action).then(() => {
    //     console.log('Replied');
    //   });
      return action;
    },
);
```

**Comment by gismya** [comment] 2023-09-11 10:50
Thank you!

I think I've found the issue and is testing a solution.

**Comment by gismya** [comment] 2023-09-11 13:06
Thank you for the report. The issue was not Node-specific, but since it's still rare to register actions with the JavaScript client we had missed that. I've created [a PR](https://github.com/ftrackhq/ftrack-javascript/pull/141) with a fix and tests to ensure the same issue doesn't happen again.

**Comment by ffMathy** [comment] 2023-09-11 16:03
Awesome! That sounds great.

Will you make sure to include a release with this fix and Node support too? That'd be awesome! 😍

**Comment by gismya** [comment] 2023-09-11 16:07
I'm awaiting a merge of https://github.com/ftrackhq/ftrack-javascript/pull/139 and https://github.com/ftrackhq/ftrack-javascript/pull/142. The next release will only be a pre-release with the node support, and if #142 solves all the issues we had in the client (And no other major issues are found) it will then become the only stable release as well.

**Comment by gismya** [comment] 2023-09-14 19:44
The release is out!!

**Closed by gismya** 2023-09-14 19:44 UTC

**Comment by ffMathy** [comment] 2023-09-14 19:57
Oh my god! Thank you for the hard work! This is huge! The project is starting to tidy up a lot! And this is huge for us too!
